language: swift
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode8.3

osx_image: xcode9.3
xcode_project: Translate Bar.xcworkspace
xcode_scheme: Translate Bar
podfile: Podfile
cache:
- bundler
- cocoapods
before_install:
- bundle install
- bundle exec pod keys set YandexDictionaryKey $YANDEXAPITRANSLATEKEY Translate\ Bar
- bundle exec pod keys set YandexTranslateKey $YANDEXAPIDICTIONARYKEY Translate\ Bar
- pod update
install: 
- ./install_swiftlint.sh
script: 
- swiftlint
- xcodebuild clean build test -workspace Translate\ Bar.xcworkspace -scheme Translate\ Bar | xcpretty -c && exit ${PIPESTATUS[0]}
